name: Test Monitor

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install curl
        run: sudo apt-get update && sudo apt-get install -y curl

      - name: Setup and run
        run: |
          chmod +x test monitor.sh
          ./test &
          TEST_PID=$!
          echo "Started test with PID: $TEST_PID"
          sleep 5
          ./monitor.sh
          kill $TEST_PID || true

      - name: Show log
        run: |
          echo "=== monitoring.log ==="
          cat monitoring.log || echo "No log"
          echo "=== end ==="
          if grep -q "API: HTTP" monitoring.log; then
            echo "SUCCESS: API check found"
          else
            echo "FAIL: No API check in log"
            exit 1
          fi
