name: Test Monitor

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup
        run: |
          chmod +x test monitor.sh
          ./test &
          sleep 3

      - name: Run monitor
        run: ./monitor.sh

      - name: Check log
        run: |
          echo "=== monitoring.log ==="
          cat monitoring.log
          echo "=== end ==="
          if grep -q "API: HTTP" monitoring.log; then
            echo "SUCCESS: API check found in log"
          else
            echo "FAIL: API check NOT found in log"
            exit 1
          fi
